
<Test>:
    size_hint: 1, 1
    pos_hint: {'center_x': .5, 'center_y': .5}
    tab_color: "red"
    do_default_tab: False
    
    

    TabbedPanelItem:
        text: 'Main'
        BoxLayout: 
            Button:
                id:"btn"
                text: 'choisir un fichier'
                size: 70,70
                size_hint: None,None
                #pos:{'center_x':0.8, 'center_y' : 0.5}
                pos_hint:{"center_x":0.5 , "center_y":0.2}

                    
            

    TabbedPanelItem:
        id:"tab1"
        text: 'BLAST'
        BoxLayout:
            Label:
                text: 'Module de BLAST'
            Button:
                id:"btn1"
                    #regarder le .content
                text: 'Choisir un fichier fasta 1'
                size: 120,120
                size_hint: None,None
                    #pos:{'center_x':0.8, 'center_y' : 0.5}
                pos_hint:{"center_x":0.5 , "center_y":0.6}  
            Button:
                
                id:"btn2"
                #regarder le .content
                text: 'Choisir un fichier fasta 2'
                size: 120,120
                size_hint: None,None
                #pos:{'center_x':0.8, 'center_y' : 0.5}
                pos_hint:{"center_x":0.5 , "center_y":0.6}  
            Button:
                
                id:"btn3"
                #regarder le .content
                text: 'Choisir un fichier modele'
                size: 120,120
                size_hint: None,None
                #pos:{'center_x':0.8, 'center_y' : 0.5}
                pos_hint:{"center_x":0.5 , "center_y":0.6}  
    